{{- if and .Values.autoscaling.horizontal.create .Values.autoscaling.horizontal.config }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "interop-eks-microservice-chart.labels" . | nindent 4 }}
spec:
  {{- toYaml .Values.autoscaling.horizontal.config | nindent 2 }}
{{- end }}
